#!/bin/bash
set -euo pipefail

LOG="/var/log/subscribe/entrypoint.log"
mkdir -p /var/log/subscribe /etc/nginx/subscribe

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [entrypoint] $*" | tee -a "$LOG"; }

[[ -z "${V2B_BACKEND:-}" ]] && { echo "❌ V2B_BACKEND 未设置"; exit 1; }
[[ -z "${V2B_HOST:-}" ]]    && { echo "❌ V2B_HOST 未设置"; exit 1; }

is_valid_trusted_ip() {
    local value="$1"
    local addr="$value"
    local prefix=""
    local o1 o2 o3 o4 octet

    if [[ "$value" == "0.0.0.0/0" || "$value" == "::/0" ]]; then
        return 1
    fi

    if [[ "$value" == */* ]]; then
        addr="${value%/*}"
        prefix="${value#*/}"
        [[ "$prefix" =~ ^[0-9]+$ ]] || return 1
    fi

    if [[ "$addr" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        if [[ -n "$prefix" ]]; then
            (( 10#$prefix <= 32 )) || return 1
        fi
        IFS='.' read -r o1 o2 o3 o4 <<< "$addr"
        for octet in "$o1" "$o2" "$o3" "$o4"; do
            (( 10#$octet >= 0 && 10#$octet <= 255 )) || return 1
        done
        return 0
    fi

    if [[ "$addr" == *:* ]]; then
        # 逐段校验 IPv6，拒绝畸形地址：否则会被写入 real_ip.conf 导致 nginx 启动失败
        [[ "$addr" =~ ^[0-9A-Fa-f:]+$ ]] || return 1
        case "$addr" in
            *:::*)   return 1 ;;   # 三个及以上连续冒号
            *::*::*) return 1 ;;   # 出现两个 "::"
        esac
        # 单独的前导/末尾冒号（非 "::"）非法
        [[ "$addr" == :* && "$addr" != ::* ]] && return 1
        [[ "$addr" == *: && "$addr" != *:: ]] && return 1
        if [[ -n "$prefix" ]]; then
            (( 10#$prefix <= 128 )) || return 1
        fi
        local -a hextets
        local groups=0 seg
        IFS=':' read -ra hextets <<< "$addr"
        for seg in "${hextets[@]}"; do
            [[ -z "$seg" ]] && continue
            [[ "$seg" =~ ^[0-9A-Fa-f]{1,4}$ ]] || return 1
            groups=$((groups + 1))
        done
        if [[ "$addr" == *::* ]]; then
            (( groups <= 7 )) || return 1
        else
            (( groups == 8 )) || return 1
        fi
        return 0
    fi

    return 1
}

write_real_ip_conf() {
    local output="/etc/nginx/subscribe/real_ip.conf"
    local trusted_ips="${AXISNOW_TRUSTED_IPS:-${REAL_IP_TRUSTED_IPS:-}}"
    local real_ip_header="${REAL_IP_HEADER:-X-Forwarded-For}"
    local normalized count ip
    local -a invalid_ips=()

    if [[ ! "$real_ip_header" =~ ^[A-Za-z0-9-]+$ ]]; then
        log "[警告] REAL_IP_HEADER 不合法，已回退为 X-Forwarded-For"
        real_ip_header="X-Forwarded-For"
    fi

    normalized="${trusted_ips//,/ }"
    normalized="${normalized//;/ }"
    count=0

    {
        echo "# Generated by entrypoint.sh. Do not edit inside the container."
        echo "# Set AXISNOW_TRUSTED_IPS to AxisNow Edge/EIP addresses or CIDRs."

        for ip in $normalized; do
            if is_valid_trusted_ip "$ip"; then
                echo "set_real_ip_from $ip;"
                count=$((count + 1))
            else
                invalid_ips+=("$ip")
            fi
        done

        if [[ "$count" -gt 0 ]]; then
            echo "real_ip_header $real_ip_header;"
            echo "real_ip_recursive on;"
        else
            echo "# No trusted proxy IPs configured; \$remote_addr remains the direct peer IP."
        fi
    } > "$output"

    for ip in "${invalid_ips[@]}"; do
        log "[警告] 跳过不合法的 AXISNOW_TRUSTED_IPS 条目：$ip"
    done

    if [[ "$count" -gt 0 ]]; then
        log "真实客户端 IP 已启用：信任 $count 个回源地址，Header=$real_ip_header"
    else
        log "真实客户端 IP 未启用：未配置 AXISNOW_TRUSTED_IPS"
    fi
}

# ── 优先从 admin_settings.json 加载配置（后台设置 > .env 环境变量）────
# admin 后台修改设置时会写入 admin_settings.json（持久化在 gw_config volume）
# 容器重启后用此处的值重新生成 protect.conf，保证后台修改不丢失
ADMIN_SETTINGS_JSON="/etc/nginx/subscribe/admin_settings.json"
if [[ -f "$ADMIN_SETTINGS_JSON" ]]; then
    _su=$(jq -r '.upstream_url  // empty' "$ADMIN_SETTINGS_JSON" 2>/dev/null || true)
    _sh=$(jq -r '.upstream_host // empty' "$ADMIN_SETTINGS_JSON" 2>/dev/null || true)
    _sp=$(jq -r '.subscribe_path // empty' "$ADMIN_SETTINGS_JSON" 2>/dev/null || true)
    if [[ -n "$_su" ]]; then
        V2B_BACKEND="$_su"
        log "上游URL  已从后台配置加载: $V2B_BACKEND"
    fi
    if [[ -n "$_sh" ]]; then
        V2B_HOST="$_sh"
    fi
    if [[ -n "$_sp" ]]; then
        SUBSCRIBE_PATH="$_sp"
        log "订阅路径 已从后台配置加载: $SUBSCRIBE_PATH"
    fi
fi

log "生成 protect.conf ..."
envsubst '${V2B_BACKEND} ${V2B_HOST} ${SUBSCRIBE_PATH}' \
    < /etc/nginx/templates-src/subscribe_protect.conf.template \
    > /etc/nginx/subscribe/protect.conf

write_real_ip_conf

cp /etc/nginx/templates-src/nginx.conf /etc/nginx/nginx.conf

# 初始化空白名单
[[ ! -f /etc/nginx/subscribe/whitelist_ips.txt ]] && touch /etc/nginx/subscribe/whitelist_ips.txt
chmod 666 /etc/nginx/subscribe/whitelist_ips.txt

# 生成白名单 geo 块
SKIP_NGINX_RELOAD=1 /scripts/reload_whitelist.sh

# 初始化空黑名单
[[ ! -f /etc/nginx/subscribe/blacklist.conf ]] && echo "# blacklist" > /etc/nginx/subscribe/blacklist.conf
[[ ! -f /etc/nginx/subscribe/blacklist.json ]] && echo "[]" > /etc/nginx/subscribe/blacklist.json
# 确保 admin 容器可写（admin php-fpm 以非 root 用户运行）
chmod 666 /etc/nginx/subscribe/blacklist.conf /etc/nginx/subscribe/blacklist.json

# 初始化自定义UA封禁
if [[ ! -f /etc/nginx/subscribe/ua_custom.conf ]]; then
    cat > /etc/nginx/subscribe/ua_custom.conf <<'UAEOF'
# 自定义封禁UA - 由 admin 自动生成
map $http_user_agent $is_custom_bad_ua {
    default 0;
}
UAEOF
fi
if [[ ! -f /etc/nginx/subscribe/ua_redirect.conf ]]; then
    cat > /etc/nginx/subscribe/ua_redirect.conf <<'UAREDEOF'
# UA 301跳转配置 - 由 admin 自动生成
map $http_user_agent $ua_custom_redirect {
    default "";
}
UAREDEOF
fi
[[ ! -f /etc/nginx/subscribe/ua_blacklist.json ]] && echo "[]" > /etc/nginx/subscribe/ua_blacklist.json
chmod 666 /etc/nginx/subscribe/ua_custom.conf /etc/nginx/subscribe/ua_redirect.conf /etc/nginx/subscribe/ua_blacklist.json

# 初始化UA白名单
if [[ ! -f /etc/nginx/subscribe/ua_whitelist.conf ]]; then
    cat > /etc/nginx/subscribe/ua_whitelist.conf <<'UAWEOF'
# UA白名单 - 由 admin 自动生成
map $http_user_agent $is_ua_whitelisted {
    default 0;
}
UAWEOF
fi
[[ ! -f /etc/nginx/subscribe/ua_whitelist.json ]] && echo "[]" > /etc/nginx/subscribe/ua_whitelist.json
chmod 666 /etc/nginx/subscribe/ua_whitelist.conf /etc/nginx/subscribe/ua_whitelist.json

# 首次拉取云IP库
if [[ ! -f /etc/nginx/subscribe/cloud_geo.conf ]]; then
    log "首次启动：拉取云厂商IP库..."
    SKIP_NGINX_RELOAD=1 /scripts/update_cloud_geo.sh || {
        log "[警告] 云IP库拉取失败，生成最小降级配置（无云IP封锁）"
        cat > /etc/nginx/subscribe/cloud_geo.conf <<'GEODEG'
# [降级模式] 首次启动网络不可用，请在管理后台手动点击「更新云IP库」
map $binary_remote_addr $whitelist_ip { default 0; }
map $whitelist_ip $subscribe_limit_key { 1 ""; default $binary_remote_addr; }
limit_req_zone $subscribe_limit_key zone=subscribe_limit:10m rate=20r/m;
geo $is_cloud_ip { default 0; }
map $http_user_agent $bad_subscribe_ua {
    default 0;
    "" 1;
    "clash" 1;
    "~^curl/" 1;
    "~^python" 1;
    "~^wget" 1;
}
GEODEG
    }
else
    log "cloud_geo.conf 已存在，跳过初次拉取"
fi

# 定时更新云IP库（基于时间戳，感知容器重启）
LAST_UPDATE_FILE="/etc/nginx/subscribe/.last_cloud_update"
if [[ -f "$LAST_UPDATE_FILE" ]]; then
    _LAST=$(cat "$LAST_UPDATE_FILE" 2>/dev/null || echo 0)
    _NOW=$(date +%s)
    if (( _NOW - _LAST > 604800 )); then
        log "云IP库超过7天未更新，立即更新..."
        SKIP_NGINX_RELOAD=0 /scripts/update_cloud_geo.sh && date +%s > "$LAST_UPDATE_FILE" || log "[警告] 更新失败"
    fi
else
    date +%s > "$LAST_UPDATE_FILE"
fi
(
    while true; do
        sleep 604800
        log "定时更新云IP库..."
        SKIP_NGINX_RELOAD=0 /scripts/update_cloud_geo.sh && date +%s > "$LAST_UPDATE_FILE" || log "[警告] 定时更新失败"
    done
) &

log "启动 nginx reload watcher..."
/scripts/nginx_reload_watcher.sh &

log "启动 nginx..."
exec nginx -g 'daemon off;'
